### PR TITLE
Cleanup some of our actions

### PR DESCRIPTION
**Pull request by bevns**
### deploy-branch

- Output custom message if someone attempts to run `.deploy noop`
- Don't need to log `git branch` anymore
- Change name from `demo` to `deploy`

### docker-img

- Switch to run on `workflow_dispatch` only. With Branch Deploy we no longer need to deploy when PR's are merged to main. Left the manual approach for now incase anything comes up with branch deploys. 

### simulate-games

- only run when a push happens a branch that targets main and includes changes to files in the `snakes` directory.

### CODE REVIEW

**Review by djdefi — APPROVED** [review]

**Comment by bevns** [comment]
.deploy

**Comment by bevns** [comment]
.deploy noop

**Comment by bevns** [comment]
.deploy

**Comment by bevns** [comment]
.deploy

**Comment by bevns** [comment]
.deploy

**Comment by bevns** [comment]
.deploy

**Review by djdefi — APPROVED** [review]

**Comment by bevns** [comment]
.deploy

**Comment by djdefi** [comment]
.deploy

**Pull request merged**
