### PR TITLE
Base image initial test

### PR DESCRIPTION
**Pull request by djdefi**

### CODE REVIEW

**Comment by djdefi** [comment]
Before merging I think we need to also make the image build on merge to main to be tagged as `latest`

**Comment by bevns** [comment]
This looks good but we need to update it now to reflect the new pinned versions in main.

**Comment by bevns** [comment]
.deploy noop

**Comment by bevns** [comment]
.deploy noop

**Review by bevns — DISMISSED** [review]

**Comment by djdefi** [comment]
.deploy

**Comment by djdefi** [comment]
.deploy

**Review by bevns — APPROVED** [review]

**Comment by djdefi** [comment]
.deploy

**Pull request merged**
