### PR TITLE
Create new PR workflow to help with deployments

### PR DESCRIPTION
**Pull request by bevns**
Adds a workflow to help with the new branch deployment process

### CODE REVIEW

**Comment by bevns** [comment]
.deploy

**Review by djdefi — DISMISSED** [review]

**Comment by djdefi** [comment]
.deploy

**Comment by djdefi** [comment]
.deploy

**Comment by bevns** [comment]
.wcid

**Comment by bevns** [comment]
.unlock

**Review by djdefi — DISMISSED** [review]

**Review by djdefi — APPROVED** [review]

**Comment by bevns** [comment]
.deploy

**Pull request merged**
