### PR TITLE
Add snakes and hazards to board object

### PR DESCRIPTION
**Pull request by bevns**
This adds quite a lot and I can add more context later but it should allow the python snake to live longer using the pathfinding logic. 

There are still quite a few bugs but we can tackle those in follow up PRs. 

py-snake-surviving

### CODE REVIEW

**Comment by djdefi** [comment]
No output on the test run makes me thing something maybe broken. It is running with the arcade map / wrapped mode and a larger than normal map size for summer league

**Comment by bevns** [comment]
Ya.. it didn't even run on the last few pushes like I expected it to. Do you think this snake is breaking it? Nothing else has really changed right? I'll find some time to debug as I suspect something in this snake may be causing it.

**Comment by bevns** [comment]
```
2022/06/16 03:21:49 invalid character '<' looking for beginning of value
```

Looks like it is this snake and occurs when the snake logic runs into this error:

```
IndexError: list index out of range
```

**Comment by djdefi** [comment]
> Ya.. it didn't even run on the last few pushes like I expected it to. Do you think this snake is breaking it? Nothing else has really changed right? I'll find some time to debug as I suspect something in this snake may be causing it. 

The output doesn't repeat if it is the same as on the prior commit, which is only likely if it is broken somehow. 

We need to make error output more apparent in CI somehow also

**Comment by bevns** [comment]
```IndexError: list index out of range``` were occurring when there was no valid path given a start and end (x,y). The logic could be improved but for now I added a quick workaround that chooses a random move when that occurs. 

I am expecting that to fix the game simulation output as well.

**Review by djdefi — APPROVED** [review]

**Comment by bevns** [comment]
@djdefi updated this again with some logic that allows the Python snake to navigate the new maze map. 

py-maze

Still to do is teach it how to wrap around the board. We may need to look into creating a fork of the pathfinding library so we can tweak it to allow wrapping. 

Also need to work on target cell for moves so it knows when to find food and such. Is still a pretty basic snake overall.

**Review by djdefi — APPROVED** [review]

**Comment by bevns** [comment]
Looks like there are some more errors preventing the simulation games from completely successfully. I'd like to address those before merging.

**Pull request merged**
