### PR TITLE
don't check for changes if deploying main

### PR DESCRIPTION
**Pull request by bevns**
This is an attempt at fixing https://github.com/es-na-battlesnake/snakes/issues/300

### CODE REVIEW

**Comment by bevns** [comment]
.deploy

**Comment by bevns** [comment]
.deploy

**Review by djdefi — APPROVED** [review]

**Comment by bevns** [comment]
.deploy

**Comment by bevns** [comment]
.deploy

**Comment by djdefi** [comment]
.deploy

**Comment by djdefi** [comment]
.deploy

**Comment by bevns** [comment]
.deploy

**Pull request merged**
